# Generated by Django 4.0 on 2022-01-19 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_blogpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
    ]
