# Generated by Django 4.0 on 2022-01-22 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_delete_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='thumbnail',
        ),
    ]
