# Generated by Django 4.0 on 2022-01-22 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_alter_contact_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
