# Generated by Django 4.0 on 2022-01-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
