# Generated by Django 4.0 on 2022-01-22 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogpost',
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
        migrations.DeleteModel(
            name='OrderUpdate',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
