# Generated by Django 4.0 on 2022-01-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_preparation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='preparation',
        ),
    ]
