# Generated by Django 4.0 on 2022-01-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_delete_preparation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prepare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=50)),
                ('youremail', models.CharField(max_length=10)),
                ('yourphone', models.CharField(max_length=10)),
                ('youraddress', models.CharField(max_length=50)),
                ('yourspecialnote', models.CharField(max_length=50)),
                ('yourcity', models.CharField(max_length=50)),
                ('yourstate', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=50)),
                ('drugname', models.CharField(max_length=50)),
                ('potency', models.CharField(max_length=50)),
                ('prepared', models.CharField(max_length=50)),
                ('quantity', models.CharField(max_length=50)),
            ],
        ),
    ]
